### ISSUE TITLE
Testcase: Live data ingestion

### ISSUE THREAD

**Issue by Slartibartfast27** [Zuehlke/SHMACK#5]
A testcase exists, which ingests current (live twitter data).
Assertion: 1000 twitter messages are ingested and can be retrieved from a database (likely cassandra)

**Comment by mspringma** [comment]
https://github.com/Zuehlke/hackzurich-sensordataanalysis/tree/master/KafkaToCassandra shows an example of Stream processing in Spark writing to Cassandra.
Not a minimal test case, but still probably sufficient.

Reading live Twitter stream and reading to Cassandra is implemented in https://github.com/SamuelBucheliZ/SHMACKCamp2016/tree/master/AkkaTwitter/src/main/scala/com/zuehlke/camp/shmack
