### ISSUE TITLE
Testcase: Test data ingestion

### ISSUE THREAD

**Issue by Slartibartfast27** [Zuehlke/SHMACK#6]
A testcase exists, which ingests the checked in constant twitter data.
Assertions: 
- 1000 twitter messages are ingested and can be retrieved from a database (likely cassandra)
- content of 2 twitter messages by id

**Comment by mspringma** [comment]
Now much better handled by https://github.com/Zuehlke/hackzurich-sensordataanalysis/tree/master/sensor-ingestion
However, a simple documented and automated test case may still be nice.
But that would be something different from is described in here, so closing.
